### ISSUE TITLE
Increase the maximum number of columns returned by the KQL module

### ISSUE THREAD

**Issue by piaudonn** [briandelmsft/SentinelAutomationModules#146]
I know that we can massage the data to make it fit in 5 columns. But after some tries, I find it easier to have let say 10 columns in the KQL output and filter the data afterward in a Data Filter or HTML Table (depending on what the purpose of the data is).
Anyhow, totally arbitrarily I suggest a maximum of 10 columns :)

**Comment by briandelmsft** [comment]
Ideally I'd like all columns but the structure of the return from the log analytics endpoint is unusual with a separate arrarys returned, one of columns and the other of rows.  The only other option I can think to build the table dynamically is some kind of nested loop.  I'd like to revisit the way that works entirely so that it can return all columns from the query if possible

**Comment by piaudonn** [comment]
I have a working version here: https://gist.github.com/piaudonn/a90ebb852422508dd3e7883dcc07a915
I am not sure if that's the most elegant way to do it, but it does the job.
