### ISSUE TITLE
Add STAT Workbook to Sentinel Workbooks list

### ISSUE THREAD

**Issue by briandelmsft** [briandelmsft/SentinelAutomationModules#252]

**Comment by piaudonn** [comment]
**⛔ Will not fix**

**📝 Summary of our discussion**

To show up in the workbooks blade we need the following two pre-requisites:
1. The workbook has to be deployed in the same resource group as the Log Analytics workspace on which Sentinel is deployed. Since the workbook is deployed at the same time as the rest of the solution, we can't require the user to scope the Sentinel RG as it might be too limited.
2. Even if in certain case the condition 1 is met, we still need to define the `sourceId` parameter in the ARM template with the identifier of the workspace where Sentinel is deplopyed. Although that could be asked during the solution deployement, it becomes to uncertain that all the conditions would be met for the workbook to finally show up in the My template section in the workbooks blade.

🙅 **As a result, we won't fix this.**

We can however update the documentation of the workbook to reflect what would be the manual steps one may follow to make the workbook appear in the blade. Issue #254 will address this instead.
