### ISSUE TITLE
Add 3rd party playbooks as STAT modules

### ISSUE THREAD

**Issue by over2under3** [briandelmsft/SentinelAutomationModules#297]
**Is your feature request related to a problem? Please describe.**
I'm looking for a way to add 3rd party playbooks into the portfolio which can be leverages by the base template
 
For example, the Sentinel github repository has 3rd party VirusTotal and crowdstrike playbooks already created:

- https://github.com/Azure/Azure-Sentinel/tree/master/Playbooks/Get-VirusTotalDomainReport
- https://github.com/Azure/Azure-Sentinel/tree/master/Playbooks/CrowdStrike

**Describe the solution you'd like**

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by briandelmsft** [comment]
I see this as being both an input and output challenge

1. You may want to consume inputs from other Playbooks into something using STAT (ie, status of the virus total report)
2. You may want to use outputs from STAT to trigger another playbook (ex. if STAT finds something, run the block user playbook)

It sounds like your issue is focused on 1, but I would like to discuss 2 as well.

For 1, we don't really have an option in STAT today as Playbooks don't have consistent outputs we can rely on.  One option may be to use tags/labels on the incident.  For example, by making a small change to the Virus Total or CrowdStrike playbooks to ensure a specific tag/label is added based on what it finds.  Then we can have STAT consume those tags/labels and make them available for further decision making.  We would leverage automation rules to sequence it so that the VT/CS playbook runs first, and then STAT runs after when the tags/labels would be available to consume.  Thoughts?

For 2, this can be done today (though not really documented) by using the tags/labels approach.  Have STAT run first, if it finds something set a tag like 'BlockUser', then use automation rules to run the block user playbook after the STAT playbook but only if the 'BlockUser' tag is present.  That way the block only happens when STAT directs it.  This at a minimum needs to be documented.  The other option for 2 which isn't available today would be to build a new STAT module that uses the [Run Playbook API](https://docs.microsoft.com/rest/api/securityinsights/preview/incidents/run-playbook).  This module would need an input of the resource ID of the Playbook you wish to run.  This would avoid the need to tag and have a second automation rule which I think makes this a more elegant solution.  Thoughts?

**Comment by briandelmsft** [comment]
I will track the Run Playbook API integration separately in #299

**Comment by briandelmsft** [comment]
With the addition of the Run playbook module which allows for STAT to run other Sentinel playbooks on the same incident, and the addition to the scoring module to allow for custom inputs to be added to score calculations I think we've covered this one.  If there's more specific asks on integration please open a new issue with additional details
