### ISSUE TITLE
Permissions on Graph Explorer?

### ISSUE THREAD

**Issue by noapocalypse** [briandelmsft/SentinelAutomationModules#331]
Hi,

After running the deployment and the PS1 script and attempting to run the sample playbook i hit an error on one of the first commands.

![image](https://user-images.githubusercontent.com/6807001/201921686-dde5962a-d736-4f2a-a5ef-2bd812968eea.png)

I believe this is an issue with graph explorer permissions for the user running the playbook (although i am new to this and happy to be corrected)

I was able to resolve this by editing consent on the following

![image](https://user-images.githubusercontent.com/6807001/201922463-1e9e9eea-548c-4b81-a99c-518ff360f4ef.png)

Is this something that needs to be mentioned or something that i've missed?

Cheers

**Comment by briandelmsft** [comment]
Hi @noapocalypse the issue you ran into was likely due to a stale token cached in the Logic app which did not have sufficient permissions.  After the token expired, a new one was issued which had the relevant permissions.  After running GrantPermissions.ps1 the Logic app may continue to fail temporarily for a period of time (usually less than an hour).

The changes in Graph Explorer would have had no impact on STAT as each STAT module runs under its own managed identity.

To review the permissions granted to the Base-Module in the Azure Portal navigate to 

1. Azure AD -> Enterprise Applications
2. Change the Application type filter to 'Managed Identities'
3. Search for and select Base-Module
4. From the left hand pane click 'Permissions'

You should see 3 permissions grants of the type 'Application'

![image](https://user-images.githubusercontent.com/68655382/201938310-ae79cbc0-eee3-42d3-93f7-32b6e1c234c8.png)

These are the only permissions grants that the Base-Module needs to operate.  The changes you made via Graph explorer would have been delegated consent grants under the Graph Explorer app which the Base-Module does not have access to.

We should probably add a section to the doc on Troubleshooting to help with this type of situation.

**Comment by piaudonn** [comment]
#333 will address that to some extent.

**Comment by noapocalypse** [comment]
Ahh cheers, appreciate this :) Thanks for the fast feedback
