### ISSUE TITLE
[QUESTION] Filter alerts out of related alerts?

### ISSUE THREAD

**Issue by mikedizzle** [briandelmsft/SentinelAutomationModules#375]
In the related alerts module, what would be the simplest way to filter out alerts from being scored that we know are just noise? I really love the solution but there are alerts that are pushing the score up too far.

**Comment by briandelmsft** [comment]
Hi @mikedizzle, there's only built in way to filter out alerts is to turn off matching based on one of the criteria (IP, Account or Host).  For other criteria, it could be done by using a Filter array step and then rebuilding the output from the module before scoring it, but it would be somewhat complex to do.  I am opening to adding an easier capability but will need more information about your situation.

In the past the only noisy alerts scenario I'm really aware of is when we match alerts on IP, and the IP happens to be a common IP like a corporate egress IP, then many alerts may relate.  While the related alerts module can turn off matching by IP, it's not able to turn off matching by specific IPs, while leaving it on for all others.

Can you elaborate on how you determine them to be noisy? or how you would like them to be filtered out?  Are we talking about filtering out alerts with certain names?  Alerts from certain providers? on something else entirely?

It's possible to build in some functionality to do the above... we could even build in the ability to add some custom KQL into the module such that when we query the SecurityAlert table you could filter out almost anything you want.

**Comment by mikedizzle** [comment]
Maybe I'm not using it like I should, but we have alerts for eDiscovery searches that come through from M365 Defender. They're good from an auditing perspective but when they are referenced by STAT, there's so many of them for a given person sometimes, that they stack the score too high. I think I've gotten around this for now by filtering them out of the automation rule that kicks STAT off, but I feel like they are still going to be brought in by related alerts module at some point. 
I had also started out with a score multiplier of 5 for related alerts and I've put that at 1 to see if that helps. User Riskiness and the MDE modules are more important to us right now. 

I think the ability to KQL out what we don't want to be included in the related alerts scoring would be awesome for those of us who are not programmatically inclined. 😅

**Comment by briandelmsft** [comment]
@mikedizzle thanks for the additional information.

This is where things get tricky.  I see your point where someone fires an incident for doing an eDiscovery search, that finds a lot of other eDiscovery searches because that's part of the person's job, it doesn't really add to the overall risk.  However, if we filter out eDiscovery alerts completely from that module then we run the risk of a user who has some other suspicious account activity which fires off STAT and then we don't link in the eDiscovery searches that user performed.

There's a few options available with what's there today:

#### Use Multiple STAT Triage Playbooks

Using a different triage playbook for different types of incidents like the eDiscovery, would allow you to change criteria to adjust for the uniqueness of a specific incident.  For example, in the eDiscovery case if you had a STAT triage specific to that you could either

- turn off the related alerts module function to link alerts by account
- you could not evaluate that module at all for those types of incidents.
- you could incorporate a watchlist of users who are expected to do eDiscovery searches and then apply a high negative weighting to the Watchlist module during scoring which will bring the risk score down for those users


#### Change the related alerts scoring to ScorePerItem = No

With this setting in the scoring module, the volume of related alerts won't impact the score.  Only the highest severity alert + the number of MITRE tactics across all related alerts are used to calculate the score.  This tends to provide a more consistent score output for the related alerts module so it won't have as much influence when many alerts are found, but will still provide significant weight if many MITRE tactics are found

#### Going forward

I do think there's value in adding some KQL customization to the related alerts module.  I'll do some investigation on this to see what it would look like

**Comment by briandelmsft** [comment]
@mikedizzle the ability to filter alerts directly in the related alerts module is now available in the latest release.  See https://github.com/briandelmsft/SentinelAutomationModules/tree/main/Modules/RelatedAlerts#alert-filtering for details on how to use it
