### ISSUE TITLE
[QUESTION] Risk Scoring Module Errors

### ISSUE THREAD

**Issue by mikedizzle** [briandelmsft/SentinelAutomationModules#383]
I occasionally get the following error from the Risk Scoring Module. I'm curious if you think it's my logic app(s) or is there an actual bug? I really notice it on a Defender for Cloud Incident with the title of "Traffic detected from IP addresses recommended for blocking"

Thoughts?

```
{
  "error": {
    "code": "BadRequest",
    "message": "Http request failed: the server did not respond within the timeout limit. Please see logic app limits at https://aka.ms/logic-apps-limits-and-config#http-limits."
  }
}
```

**Comment by briandelmsft** [comment]
@mikedizzle if you look at the Calculate-RiskScore logic apps run history, is it occasionally taking more than 2 minutes to complete?  The Logic Apps customer connector seems to have issues when the module takes more than 2 minutes to execute.

If that is the case there's 2 potential workarounds for the issue.

If you are sending more than 20 inputs to the scoring module, which is unlikely but possible, you may want to edit the Calculate-RiskScore logic app and inside the logic app locate the 'For each' step.  On that steps context menu, click Settings.  Then, set concurrency control to on and increase the degree of parallelism to 50.  Click done and then save the logic app.  This should result in the logic app running faster.

If you are sending less than 20 items to the risk scoring logic app but still exceeding the the 2 minutes there are 2 options:
Consider changing the scoreperitem to no on some of the input data.  This will impact the score (see the docs on the scoring module), but it will speed up processing.  

The other options is to call the Calculate-RiskScore module through the Logic Apps connector (instead of the STAT connector).  When calling through the Logic Apps connector, it will support async processing which will allow the caller to wait longer than 2 minutes for the response.

**Comment by mikedizzle** [comment]
Thanks for these suggestions. I'll try them out.
