### ISSUE TITLE
[QUESTION] Sporadic errors from MDE

### ISSUE THREAD

**Issue by mikedizzle** [briandelmsft/SentinelAutomationModules#388]
I get the following errors from the MDE module. I doubt it's a bug with the STAT logic apps. Do you know where I should look to troubleshoot?
```
{
  "error": {
    "code": "NoResponse",
    "message": "The server did not receive a response from an upstream server. Request tracking id '08585214660638237722649269550CU27'."
  }
}
```

**Comment by mikedizzle** [comment]
Just as an FYI I do 30-day lookback.

**Comment by mikedizzle** [comment]
Ok, I'll take a look a bit later. I recently deployed from the incident_tasks branch to get the GCC endpoints. Did that branch have the updated logic app?

**Comment by mikedizzle** [comment]
The timing of the MDE calls doesn't exceed 20 seconds. I get 414 http errors. Seems to be in the MDE - Get Machines by Id in the foreach account under the Scope Account step. 

![image](https://user-images.githubusercontent.com/25623585/229029197-f95db687-b4f9-44ed-b9f5-f4bc691f4b9b.png)

**Comment by briandelmsft** [comment]
> Ok, I'll take a look a bit later. I recently deployed from the incident_tasks branch to get the GCC endpoints. Did that branch have the updated logic app?

Yes, that branch included the efficiency update in the MDE module.

> The timing of the MDE calls doesn't exceed 20 seconds. I get 414 http errors. Seems to be in the MDE - Get Machines by Id in the foreach account under the Scope Account step.

I see, this is a new one @mikedizzle , Can you tell me how many device ids are in that array passed as $filter?  The filter is passed as part of the query string, and most systems allow 2000 characters to be passed in total.  The base URI is about 128 characters + 42 characters per device id.  If I do the math on that you should be able to pass about 44 devices before hitting the 2000 characters

**Comment by briandelmsft** [comment]
@mikedizzle looking into this a bit further I found 2 likely causes for this.  The first (which I found second), is that the update to support GCC introduced a regression where the device list was not deduplicated.  This resulted in the list being larger than it needed to be which could easily and on its own cause the RequestUriTooLong error (#390)

The other issue, is that if a user has logged onto a legitimately large number of unique devices, then the list will still be very large and could drive the same RequestUriTooLong error (#389)

#390 has already been fixed in the incident_tasks branch and that alone should greatly reduce the instances of this error.  Please redeploy using the same instructions you had to deploy from this branch initially. #389 is much less likely to cause this problem, but we will also take care of that one soon.

**Comment by briandelmsft** [comment]
@mikedizzle This is now part of the main branch so you can use the main [deployment link](https://aka.ms/mstatdeploy).  You will still have to use advanced mode to change to the GCC endpoints, but you can leave the branch as main

**Comment by briandelmsft** [comment]
Please reopen if you continue to have this issue, it should be resolved for all but the most exceptional of cases where users have logged onto 40+ devices (maybe even more) with the code that's already in the main branch of the repo
