### ISSUE TITLE
[BUG] Threat Intel Module - "LookbackInDays" parameter missing

### ISSUE THREAD

**Issue by NobleWolf** [briandelmsft/SentinelAutomationModules#463]
**Describe the bug**
The wiki shows the Threat Intel Module shoudl have a paramtere called ``LookbackInDays`` but that is not available in our STAT v2 deployment.

**Module Name**
Threat Intel Module
from STAT v2.0.8

**To Reproduce**
1. Deploy following [STAT v2 instructions here](https://github.com/briandelmsft/SentinelAutomationModules/wiki/Deployment)
2. Open Sample Triage playbook
3. Click the "Threat Intel Module"
4. See that there are only 7 paramters and the ``LookbackInDays`` paramter is missing.

**Expected behavior**
To set the ``LookbackInDays`` paramter.

**Screenshots**
![image](https://github.com/user-attachments/assets/c14d0516-a1dd-4af6-b674-dce462c24dc7)
![image](https://github.com/user-attachments/assets/9dddbf32-801c-49d7-bc11-3a072a30b212)
![image](https://github.com/user-attachments/assets/8ba5f1c0-6233-4c5d-8a8e-766e1108f1ab)

**Additional context**
Let me know if I can provide more information.

**Comment by briandelmsft** [comment]
@NobleWolf Thanks. I have removed that from the wiki.  We removed the option as there is no compelling reason to do anything other than a 14 day search as the intent is to search all active TI.  All active TI indicators are repopulated every 14 days for compatibility with Analytics rules since their max lookback is 14 days.
